apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-config
  namespace: agrosolutions-ingestion
data:

  ASPNETCORE_ENVIRONMENT: "Production"
  RABBITMQ_QUEUE: "sensor_readings"
  INFLUX_URL: "http://influxdb-influxdb2.observability:8086"
  INFLUX_BUCKET: "default"
  INFLUX_ORG: "influxdata"
  INFLUX_MEASUREMENT: "sensor_reading"
  RABBITMQ_HOST: "rabbitmq.messaging"
  