apiVersion: v1
kind: Secret
metadata:
  name: ingestion-secret
  namespace: agrosolutions-ingestion
type: Opaque
stringData:
  INFLUXDB_TOKEN: "#{InfluxToken}#"
  RABBITMQ_USER: "#{RabbitMqUser}#"
  RABBITMQ_PASS: "#{RabbitMqPassword}#"
  JWT_ISSUER: "#{JwtIssuer}#"
  JWT_AUDIENCE: "#{JwtAudience}#"
  JWT_KEY: "#{JwtKey}#"