apiVersion: v1
kind: Secret
metadata:
  name: ingestion-secret
  namespace: agrosolutions-ingestion
type: Opaque
stringData:
  INFLUXDB_TOKEN: "#{InfluxDBToken}#"
  RABBITMQ_CONNECTION_STRING: "#{RabbitmqConnectionString}#"
  JWT_ISSUER: "#{JwtIssuer}#"
  JWT_AUDIENCE: "#{JwtAudience}#"
  JWT_KEY: "#{JwtKey}#"